export const TYPES = {
  // GET en AXIOS
  READ_STATE: "READ_STATE",
  //POST en AXIOS
  ADD_TO_CART: "ADD_TO_CART",
  //DELETE en AXIOS
  REMOVE_ONE_PRODUCT: "REMOVE_ONE_PRODUCT",
  REMOVE_ALL_PRODUCTS: "REMOVE_ALL_PRODUCT",
  CLEAR_CART: "CLEAR",
};
